# You can have multiple profiles to group your configuration. E.g., if you use multiple
# projects, you can create two separate profiles each with its own role appropriate API
# key. When you invoke the CloudTruth CLI tool, you can pass an argument to choose
# which profile to load. Profiles can inherit values from other profiles by using the
# `source_profile` setting, providing it with the name of another profile. Profile
# chains can be arbitrarily deep, but may not contain cycles.


updates:
  check: true
  last_checked: 2024-06-18

profiles:
  default:
    source_profile: demo-staging
    request_timeout: 180

  demo-prod:
    server_url: "https://api.cloudtruth.io"
    api_key: "foo"
    description: "production demo"

  demo-staging:
    server_url: "https://api.staging.cloudtruth.io"
    api_key: "bar"
    description: staging demo
