name: 'CloudTruth Configure'
on: workflow_dispatch

jobs:
  configure-action-test:
    runs-on: ubuntu-latest
    steps:
      - uses: dwdozier/configure-action@v2.2.7
        with:
          apiKey: "${{ secrets.CLOUDTRUTH_API_KEY }}"
          project: action-push-testing
          environment: dev1
          server: https://api.staging.cloudtruth.io
      - name: dump env
        run: |
          printenv | sort
